---
# hardening
#
#
- name: Retrieve package facts
  package_facts:
    manager: "auto"
  tags: libuser_sha512

- name: Retrieve service facts
  service_facts:
  tags:
    - hardening_crontab
    - hardening_kernel_modules
    - unwanted_svc

# STIG 010220
- name: NSA 2.3.3.5 Upgrade Password Hashing Algorithm to SHA-512
  template:
    src: 'libuser.conf.j2'
    dest: '/etc/libuser.conf'
    mode: '0640'
    owner: 'root'
    group: 'root'
  when:
    - "'libuser' in ansible_facts.packages"
  tags: libuser_sha512

- name: Remove unwanted packages
  package:
    name: "{{ unwanted_pkg }}"
    state: absent
  tags: unwanted_pkg

- name: Install wanted packages
  package:
    name: "{{ wanted_pkg }}"
    state: present
  tags: wanted_pkg

- name: Disable unwanted services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  delay: 3
  register: result
  retries: 3
  until: result is not failed
  when: "'{{ item }}' in ansible_facts.services"
  with_items: "{{ unwanted_services }}"
  tags: unwanted_svc

- import_tasks: package_manager.yml
  tags: hardening_pkg_manager

- import_tasks: crontab.yml
  tags: hardening_crontab

- import_tasks: limits.yml
  tags: hardening_limits

- import_tasks: mounts.yml
  tags: hardening_mounts

- import_tasks: ssh.yml
  tags: hardening_ssh

- import_tasks: auditd.yml
  tags: hardening_auditd

- import_tasks: kernel_modules.yml
  tags: hardening_kernel_modules

- import_tasks: kernel_hardening.yml
  tags: hardening_kernel

- import_tasks: minimize_access.yml
  tags: hardening_access

...
